name: Package And Publish


on:
  push:
    branches: [ docs ]


jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x] # 配置所需node版本

    steps:
      
      - uses: actions/checkout@v2
        with:
          ref: docs
          fetch-depth: 0

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies  # 安装依赖
        run: yarn install
      
      - name: Packaging
        run: yarn run docs:build
        
      # - name: Commit files And Push
      #   run: |
      #        cd docs/.vuepress/dist
      #        echo 'github.blog.ran-ding.ga'> CNAME
      #        git init
      #        git config --global user.name roiding
      #        git config --global user.email dingran@ran-ding.ga
      #        git add -A
      #        git commit -m 'deploy'
      #        git push --quiet --force https://oauth2:${{secrets.GH_TOKEN}}@github.com/roiding/roiding.github.io.git master:master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: roiding/roiding.github.io
          branch: master
          folder: dist
          token: ${{ secrets.GH_TOKEN }}
          single-commit: true 
